apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infisical
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://dl.cloudsmith.io/public/infisical/helm-charts/helm/charts/
    chart: infisical-standalone
    targetRevision: 0.5.2
    helm:
      values: |
        infisical:
          image:
            repository: infisical/infisical
            tag: "v0.66.2-postgres"
            pullPolicy: IfNotPresent
          replicaCount: 1

          # Use existing secret with connection URIs
          existingSecret: infisical-secrets

        ingress:
          enabled: false

        # Disable embedded databases - use our own
        postgresql:
          enabled: false

        redis:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: infisical
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
