apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infisical-db
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:0xAaCE/HomeLab.git
    targetRevision: main
    path: apps/infisical-db
  destination:
    server: https://kubernetes.default.svc
    namespace: infisical
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
