apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: phone-games
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:0xAaCE/phone_games.git
    targetRevision: main
    path: ops/k8s/base
  destination:
    server: https://kubernetes.default.svc
    namespace: phone-games
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  ignoreDifferences:
  - group: ""
    kind: Secret
    name: infisical-auth
    namespace: phone-games
