apiVersion: apps/v1
kind: Deployment
metadata:
  name: infisical
  namespace: infisical
spec:
  replicas: 1
  selector:
    matchLabels:
      app: infisical
  template:
    metadata:
      labels:
        app: infisical
    spec:
      containers:
      - name: infisical
        image: infisical/infisical:latest-postgres
        ports:
        - containerPort: 8080
          name: http
        env:
        # Secrets (must be defined first for variable substitution)
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: infisical-secrets
              key: db-password
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: infisical-secrets
              key: redis-password

        # Database
        - name: DB_CONNECTION_URI
          value: "postgres://infisical:$(DB_PASSWORD)@postgres:5432/infisical"

        # Redis
        - name: REDIS_URL
          value: "redis://:$(REDIS_PASSWORD)@redis:6379"

        # Encryption
        - name: ENCRYPTION_KEY
          valueFrom:
            secretKeyRef:
              name: infisical-secrets
              key: encryption-key
        - name: AUTH_SECRET
          valueFrom:
            secretKeyRef:
              name: infisical-secrets
              key: auth-secret

        # Application
        - name: SITE_URL
          value: "https://secrets.0xaace.xyz"
        - name: TELEMETRY_ENABLED
          value: "false"

        # Probes temporarily disabled for initialization
        # livenessProbe:
        #   httpGet:
        #     path: /api/status
        #     port: 8080
        #   initialDelaySeconds: 120
        #   periodSeconds: 10
        #   failureThreshold: 5

        # readinessProbe:
        #   httpGet:
        #     path: /api/status
        #     port: 8080
        #   initialDelaySeconds: 30
        #   periodSeconds: 5
        #   failureThreshold: 12

        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: infisical
  namespace: infisical
spec:
  selector:
    app: infisical
  ports:
  - port: 8080
    targetPort: 8080
    name: http
